spring:
  application:
    name: deliverytouroptimizerv2

  profiles:
    active: ${ACTIVE_PROFILE}

  jpa:
    open-in-view: false

  ai:
    ollama:
      base-url: ${AI_URL}
      chat:
        options:
          model: ${AI_MODEL}

logging:
  level:
    org:
      springframework: INFO

server:
  port: 8080

optimizer:
  type: ai #nearest / clark / ai