spring:
  application:
    name: deliverytouroptimizerv2

  profiles:
    active: ${ACTIVE_PROFILE}

  jpa:
    open-in-view: false

logging:
  level:
    org:
      springframework: INFO

server:
  port: 8080

optimizer:
  type: nearest #nearest / clark